# Generated by Django 5.1.2 on 2024-11-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='d4.jpg', null=True, upload_to='products/'),
        ),
    ]
