# Generated by Django 5.1.2 on 2024-12-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiApp', '0005_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/your-cloud-name/image/upload/v1606355678/default-placeholder.jpg', null=True),
        ),
    ]
