# Generated by Django 5.1.2 on 2024-12-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiApp', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dtdsnmdfw/image/upload/v1733191506/default-placeholder.jpg_wfxcut.jpg', null=True),
        ),
    ]
